layout_spectrum: 0.0952381
color:
  saturation: 0.5807174
  brandStrength: 0.6672933
  lightness: 0.8019733
  rhythmicContrast: 0.3124681
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.4266917
name: the brentwood farm
